language: android
android:
    components:
        - platform-tools
        - tools

        - build-tools-28.0.3

        - android-23
        
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

before_script:
        - chmod +x gradlew

script: "./gradlew build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 9ef8b9d8bcdebdfa66cd218ee543a53b9c00e126  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master